// SNACK
export const SHOW_SNACK = "SHOW_SNACK";
export const HIDE_SNACK = "HIDE_SNACK";
// DIALOG
export const SHOW_DIALOG = "SHOW_DIALOG";
export const HIDE_DIALOG = "HIDE_DIALOG";
export const LOADING_DIALOG = "LOADING_DIALOG";
export const STOP_LOADING_DIALOG = "STOP_LOADING_DIALOG";
// Language
export const CHANGE_LANGUAGE = "CHANGE_LANGUAGE";
