export interface SupportInfo {
  firstname: string;
  lastname: string;
  firstname_kana: string;
  lastname_kana: string;
  is_anonymous: boolean;
  birthday: string;
  gender_type_id: number;
  postal_code: string;
  region_id: number;
  region_name?: string;
  address: string;
  municipalities: string;
  building_name: string;
  university_name: string;
  university_club: string;
  high_school_name: string;
  high_school_club: string;
  junior_high_school_name: string;
  junior_high_school_club: string;
  favorite_competition1: string;
  favorite_competition2: string;
  favorite_competition3: string;
  favorite_team1: string;
  favorite_team2: string;
  favorite_team3: string;
  support_type?: number | null;
  support_amount?: number;
  support_type_name?: string;
  team_id: number | null;
  team_name: string;
}