version: 0.0
os: linux
files:
  - source: .
    destination: /usr/src/anyteam/
permissions:
  - object: /usr/src/anyteam/
    pattern: '*'
    owner: undo-dev
    group: undo-admin
    mode: 644
    type:
      - file
  - object: /usr/src/anyteam/
    pattern: '**'
    owner: undo-dev
    group: undo-admin
    mode: 755
    type:
      - directory
hooks:
  ApplicationStop:
    - location: ./deployment/scripts/application_stop.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: ./deployment/scripts/before_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: ./deployment/scripts/after_install.sh
      timeout: 1200
      runas: root
  ApplicationStart:
    - location: ./deployment/scripts/application_start.sh
      timeout: 300
      runas: root
