version: 0.2

env:
  variables:
    TERM: "xterm"

phases:
  build:
    commands:
      - echo Build started on `date`
      - pwd
      - ls -al
      - ls -al
artifacts:
  files:
    - '**/*'
  secondary-artifacts:
    artifact1:
      files:
        - '**/*'
